version: '3'

services:
  app:
    image: nifisample/app
    ports:
      - 80:80
    depends_on:
      - app-postgre-db
    networks:
      - nifisample

  app-postgre-db:
    image: nifisample/postgre-sql
    volumes:
      - NiFiSamplePostgreDb:/var/lib/pgsql/data/
    ports:
      - 5432:5432
    networks:
      - nifisample

  clickhouse-db:
    image: nifisample/clickhouse
    command: gosu clickhouse:clickhouse sh -c ' while :; do /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml; sleep 1; done'
    volumes:
      - NiFiSampleClickHouseDb:/var/lib/clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    networks:
      - nifisample

  nifi:
    image: nifisample/nifi
    ports:
      - 8443:8443
    environment:
      # 4 characters min
      SINGLE_USER_CREDENTIALS_USERNAME: flexberryuser
      # 12 characters min
      SINGLE_USER_CREDENTIALS_PASSWORD: jhvjhvjhvjhv
    depends_on:
      - app-postgre-db
      - clickhouse-db
    networks:
      - nifisample

volumes:
  NiFiSampleClickHouseDb:
  NiFiSamplePostgreDb:

networks:
  nifisample:
