//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.NiFiSample
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Denormalized car data.
    /// </summary>
    // *** Start programmer edit section *** (CarData CustomAttributes)

    // *** End programmer edit section *** (CarData CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class CarData : ICSSoft.STORMNET.DataObject
    {
        
        private string fBrandName;
        
        private string fCarNumber;
        
        private IIS.NiFiSample.CarType fCarBody;
        
        private System.DateTime fCarDate;
        
        private string fSparePartName;
        
        private int fSparePartQuantity;
        
        private bool fSparePartUsed = false;
        
        private string fSparePartProducingCountryName;
        
        // *** Start programmer edit section *** (CarData CustomMembers)

        // *** End programmer edit section *** (CarData CustomMembers)

        
        /// <summary>
        /// BrandName.
        /// </summary>
        // *** Start programmer edit section *** (CarData.BrandName CustomAttributes)

        // *** End programmer edit section *** (CarData.BrandName CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string BrandName
        {
            get
            {
                // *** Start programmer edit section *** (CarData.BrandName Get start)

                // *** End programmer edit section *** (CarData.BrandName Get start)
                string result = this.fBrandName;
                // *** Start programmer edit section *** (CarData.BrandName Get end)

                // *** End programmer edit section *** (CarData.BrandName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CarData.BrandName Set start)

                // *** End programmer edit section *** (CarData.BrandName Set start)
                this.fBrandName = value;
                // *** Start programmer edit section *** (CarData.BrandName Set end)

                // *** End programmer edit section *** (CarData.BrandName Set end)
            }
        }
        
        /// <summary>
        /// CarNumber.
        /// </summary>
        // *** Start programmer edit section *** (CarData.CarNumber CustomAttributes)

        // *** End programmer edit section *** (CarData.CarNumber CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string CarNumber
        {
            get
            {
                // *** Start programmer edit section *** (CarData.CarNumber Get start)

                // *** End programmer edit section *** (CarData.CarNumber Get start)
                string result = this.fCarNumber;
                // *** Start programmer edit section *** (CarData.CarNumber Get end)

                // *** End programmer edit section *** (CarData.CarNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CarData.CarNumber Set start)

                // *** End programmer edit section *** (CarData.CarNumber Set start)
                this.fCarNumber = value;
                // *** Start programmer edit section *** (CarData.CarNumber Set end)

                // *** End programmer edit section *** (CarData.CarNumber Set end)
            }
        }
        
        /// <summary>
        /// CarBody.
        /// </summary>
        // *** Start programmer edit section *** (CarData.CarBody CustomAttributes)

        // *** End programmer edit section *** (CarData.CarBody CustomAttributes)
        public virtual IIS.NiFiSample.CarType CarBody
        {
            get
            {
                // *** Start programmer edit section *** (CarData.CarBody Get start)

                // *** End programmer edit section *** (CarData.CarBody Get start)
                IIS.NiFiSample.CarType result = this.fCarBody;
                // *** Start programmer edit section *** (CarData.CarBody Get end)

                // *** End programmer edit section *** (CarData.CarBody Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CarData.CarBody Set start)

                // *** End programmer edit section *** (CarData.CarBody Set start)
                this.fCarBody = value;
                // *** Start programmer edit section *** (CarData.CarBody Set end)

                // *** End programmer edit section *** (CarData.CarBody Set end)
            }
        }
        
        /// <summary>
        /// CarDate.
        /// </summary>
        // *** Start programmer edit section *** (CarData.CarDate CustomAttributes)

        // *** End programmer edit section *** (CarData.CarDate CustomAttributes)
        [NotNull()]
        public virtual System.DateTime CarDate
        {
            get
            {
                // *** Start programmer edit section *** (CarData.CarDate Get start)

                // *** End programmer edit section *** (CarData.CarDate Get start)
                System.DateTime result = this.fCarDate;
                // *** Start programmer edit section *** (CarData.CarDate Get end)

                // *** End programmer edit section *** (CarData.CarDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CarData.CarDate Set start)

                // *** End programmer edit section *** (CarData.CarDate Set start)
                this.fCarDate = value;
                // *** Start programmer edit section *** (CarData.CarDate Set end)

                // *** End programmer edit section *** (CarData.CarDate Set end)
            }
        }
        
        /// <summary>
        /// SparePartName.
        /// </summary>
        // *** Start programmer edit section *** (CarData.SparePartName CustomAttributes)

        // *** End programmer edit section *** (CarData.SparePartName CustomAttributes)
        [StrLen(255)]
        public virtual string SparePartName
        {
            get
            {
                // *** Start programmer edit section *** (CarData.SparePartName Get start)

                // *** End programmer edit section *** (CarData.SparePartName Get start)
                string result = this.fSparePartName;
                // *** Start programmer edit section *** (CarData.SparePartName Get end)

                // *** End programmer edit section *** (CarData.SparePartName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CarData.SparePartName Set start)

                // *** End programmer edit section *** (CarData.SparePartName Set start)
                this.fSparePartName = value;
                // *** Start programmer edit section *** (CarData.SparePartName Set end)

                // *** End programmer edit section *** (CarData.SparePartName Set end)
            }
        }
        
        /// <summary>
        /// SparePartQuantity.
        /// </summary>
        // *** Start programmer edit section *** (CarData.SparePartQuantity CustomAttributes)

        // *** End programmer edit section *** (CarData.SparePartQuantity CustomAttributes)
        public virtual int SparePartQuantity
        {
            get
            {
                // *** Start programmer edit section *** (CarData.SparePartQuantity Get start)

                // *** End programmer edit section *** (CarData.SparePartQuantity Get start)
                int result = this.fSparePartQuantity;
                // *** Start programmer edit section *** (CarData.SparePartQuantity Get end)

                // *** End programmer edit section *** (CarData.SparePartQuantity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CarData.SparePartQuantity Set start)

                // *** End programmer edit section *** (CarData.SparePartQuantity Set start)
                this.fSparePartQuantity = value;
                // *** Start programmer edit section *** (CarData.SparePartQuantity Set end)

                // *** End programmer edit section *** (CarData.SparePartQuantity Set end)
            }
        }
        
        /// <summary>
        /// SparePartUsed.
        /// </summary>
        // *** Start programmer edit section *** (CarData.SparePartUsed CustomAttributes)

        // *** End programmer edit section *** (CarData.SparePartUsed CustomAttributes)
        public virtual bool SparePartUsed
        {
            get
            {
                // *** Start programmer edit section *** (CarData.SparePartUsed Get start)

                // *** End programmer edit section *** (CarData.SparePartUsed Get start)
                bool result = this.fSparePartUsed;
                // *** Start programmer edit section *** (CarData.SparePartUsed Get end)

                // *** End programmer edit section *** (CarData.SparePartUsed Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CarData.SparePartUsed Set start)

                // *** End programmer edit section *** (CarData.SparePartUsed Set start)
                this.fSparePartUsed = value;
                // *** Start programmer edit section *** (CarData.SparePartUsed Set end)

                // *** End programmer edit section *** (CarData.SparePartUsed Set end)
            }
        }
        
        /// <summary>
        /// SparePartProducingCountryName.
        /// </summary>
        // *** Start programmer edit section *** (CarData.SparePartProducingCountryName CustomAttributes)

        // *** End programmer edit section *** (CarData.SparePartProducingCountryName CustomAttributes)
        [StrLen(255)]
        public virtual string SparePartProducingCountryName
        {
            get
            {
                // *** Start programmer edit section *** (CarData.SparePartProducingCountryName Get start)

                // *** End programmer edit section *** (CarData.SparePartProducingCountryName Get start)
                string result = this.fSparePartProducingCountryName;
                // *** Start programmer edit section *** (CarData.SparePartProducingCountryName Get end)

                // *** End programmer edit section *** (CarData.SparePartProducingCountryName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CarData.SparePartProducingCountryName Set start)

                // *** End programmer edit section *** (CarData.SparePartProducingCountryName Set start)
                this.fSparePartProducingCountryName = value;
                // *** Start programmer edit section *** (CarData.SparePartProducingCountryName Set end)

                // *** End programmer edit section *** (CarData.SparePartProducingCountryName Set end)
            }
        }
    }
}
